### ISSUE TITLE
Error: The parameter "automatic_release_tag" was not set

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#14]
While running Github release:
```
Determining release tags
Error: The parameter "automatic_release_tag" was not set and this does not appear to be a GitHub tag event. (Event: refs/heads/main
```

I've tried setting:
```
on:
  push:
    tags:
      - '*'
```
And releasing with tags: `2024082200` and `latest`

**Comment by pixincreate** [comment]
Hey!

Can you fetch from latest main and try now?
You might have to go through the changes done (documentation not done yet) once before trying it out.

**Comment by 0cwa** [comment]
All I get now when releasing is:
Error
Invalid type for `on`

I also can't seem to run it from the actions tab.  I checked my syntax

**Comment by pixincreate** [comment]
Build does have a minor issue w.r.t to keys as I changed the format of storage in the end.

Workflow, I cannot see any issue here. It just works..

If your is accessible, could you please share the link for me to look at it so that I can fix it if it is an actual bug?

**Comment by 0cwa** [comment]
Ok, I sent you an invite :)

**Comment by pixincreate** [comment]
Try making https://github.com/0cwa/PixeneOS/blob/5e49fc4f9475d47af94b1f688e799a4db35a149c/.github/workflows/release.yml#L13 a string by adding double quotes and see if that works. I believe that should fix it.

**Comment by 0cwa** [comment]
[That I just "fixed the syntax on this"](https://github.com/0cwa/PixeneOS/commit/5e49fc4f9475d47af94b1f688e799a4db35a149c) was the problem lol

**Comment by 0cwa** [comment]
Anyways, I'm sure you're just working on the deployment guide still, and I probably just need to set some env variables but this is what I get now:

```
build
failed Aug 26, 2024 in 5s
2s
0s
0s
0s
0s
Run git config --global user.email  && git config --global user.name PiX
  git config --global user.email  && git config --global user.name PiX
  shell: /usr/bin/bash -e {0}
  env:
    CARGO_INCREMENTAL: 1
    RUST_BACKTRACE: short
    RUSTUP_MAX_RETRIES: 10
    DEVICE_NAME: bluejay
    INTERACTIVE_MODE: false
    REMOTE_GRAPHENEOS_VERSION: 2024082200
Error: Process completed with exit code 1.
```

**Comment by pixincreate** [comment]
You need to set your email and user name in for git.  
`secrets.EMAIL`, replace `PiX` with your name.

I believe there's something else that is resulting in this failure other than this(?)
