### ISSUE TITLE
Seems to default to checking bluejay despite different device defined

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#15]
In github actions, under `Check if a bulid already exists...`
```
Run url="https://releases.grapheneos.org/bluejay-stable"
Tag with GrapheneOS version 2024082200 already exists. Looking for assets...
Missing assets:
  - bluejay-2024082200-magisk-*.zip
  - bluejay-2024082200-magisk-*.zip.csig
  - bluejay-2024082200-rootless-*.zip
  - bluejay-2024082200-rootless-*.zip.csig
Proceeding with build to create missing assets...
```

**Comment by pixincreate** [comment]
Even if the user passes the device name from input during `workflow_dispatch`, checks look for `bluejay`. However, if you look at patch step, I believe that should be created for the device mentioned during input, right?

It would be helpful if you could post complete logs for complete context as it contains no sensitive information.

Good catch BTW.

**Comment by pixincreate** [comment]
I've made some significant changes. Not sure whether it's good practice or not. But the intention is that, main code should not modified to make it work for you or anyone else.  

User should just update an env.toml file and during run time, it is read and values from it takes precedence over default values.

**Comment by pixincreate** [comment]
Should be fixed with https://github.com/pixincreate/PixeneOS/commit/dfd9a75c22950e58f65a0bdcc3b30f287bf12dcb.

Please re-open if the issue persists.
