### ISSUE TITLE
[BUG] building magisk version expects `signature_url` to be passed that results in `get` call to fail

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#16]
Github actions, patching
```
Cloning into '.tmp/tools/my-avbroot-setup'...
`my-avbroot-setup` downloaded.
Verifying `my-avbroot-setup`...
Tool my-avbroot-setup is a directory in `.tmp`. Verified.
src/fetcher.sh: line 49: 3: unbound variable

Error: Process completed with exit code 1.
```

**Comment by pixincreate** [comment]
This is known. You get this error only when you add `Magisk`. That is because, we're not passing signature URL to get call. Since it is empty, it throws this error.  

Will fix this.
In the mean time, you can comment out `set -o nounset -o pipefail -o errexit` in `src/main.sh` to test things out.
