### ISSUE TITLE
Start of build guide/dependency list file

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#2]
So far:

You need avbroot and afsr in your PATH

Fedora/RH (Did not start with a clean system):
`sudo dnf groupinstall 'Development Tools`
`sudo dnf install libcom_err-devel xxd e2fsprogs-devel`

Ubuntu equivalent:
`comerr-dev xxd e2fsprogs libe2p-dev build-essential`

On Fedora I had to also run
`export C_INCLUDE_PATH=/usr/lib/gcc/x86_64-redhat-linux/14/include` for:

<details><summary>Build Fail</summary>
<p>

/usr/include/et/com_err.h:19:10: fatal error: 'stddef.h' file not found
  thread 'main' panicked at build.rs:57:10:
  Failed to generate bindings: ClangDiagnostic("/usr/include/et/com_err.h:19:10: fatal error: 'stddef.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

</p>
</details>

**Comment by pixincreate** [comment]
This issue is afsr specific and I already have an issue open [here](https://github.com/chenxiaolong/afsr/issues/2).

This, for me partially works on Mac but not on GitHub CI or my VM at the moment.
