### ISSUE TITLE
Cleanup Variable Doesn't Prevent Working Directory Removal

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#4]
In relation to when the error in #3 occurs, it always removed the working directory, and made it difficult to debug.  Had to comment out cleanup and the reference to it in.  But it seems like it was just running because of its inclusion in main.sh without checking on the cleanup function.

Propose adding the check into the cleanup function to keep cleanup from running when CLEANUP is set to false

**Comment by pixincreate** [comment]
Hey, thanks for this!  

I was out of thoughts on this one back when I had started this and completely forgot on `CLEANUP`. It should be fixed in [`d4ffcde`](https://github.com/pixincreate/PixeneOS/commit/d4ffcde2db8f13c43dce9e8d16122717379afebb)
