### ISSUE TITLE
Custota.zip module not downloaded

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#5]
I've worked around all the other build errors, this is the last one which has stumped me.

[*] Verifying SSH signature: .tmp/modules/custota.zip
Traceback (most recent call last):
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 919, in run
    inject_custota(
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 420, in inject_custota
    verify_ssh_sig(module_zip, module_sig, SSH_PUBLIC_KEY_CHENXIAOLONG)
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 401, in verify_ssh_sig
    with open(zip, 'rb') as f_zip:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.tmp/modules/custota.zip'

**Comment by pixincreate** [comment]
Can you provide some more info on this? I cannot reproduce this.

- Does `custota.zip` exist in `.tmp/modules`? 
- Does `custota.zip.sig` exist in `.tmp/signatures`?
- Can you share the initial download logs? You get something like below:
	```
	Constructing URL for `custota` as `custota` is non-existent at `.tmp`...
	URL for `custota`: https://github.com/chenxiaolong/custota/releases/download/v4.8/custota-4.8-release.zip
	Downloading `custota`...
	src/fetcher.sh: line 63: continue: only meaningful in a `for', `while', or `until' loop
	Extracting and granting permissions for `custota`...
	chmod: cannot access '.tmp/custota/custota': No such file or directory
	Cleaning up...
	`custota` downloaded.
	Verifying `custota`...
	Tool custota is a directory in `.tmp`. Verified.
	
	Constructing URL for `custota-tool` as `custota-tool` is non-existent at `.tmp`...
	URL for `custota-tool`: https://github.com/chenxiaolong/Custota/releases/download/v4.8/custota-tool-4.8-x86_64-unknown-linux-gnu.zip
	Downloading `custota-tool`...
	Extracting and granting permissions for `custota-tool`...
	Cleaning up...
	`custota-tool` downloaded.
	Verifying `custota-tool`...
	Tool custota-tool is a directory in `.tmp`. Verified.
	```

**Comment by pixincreate** [comment]
Found the bug, will be raising fix in a few mins
