### ISSUE TITLE
docs: add detailed documentation about PixeneOS

### ISSUE THREAD

**Issue by pixincreate** [pixincreate/PixeneOS#65]
Let's do one of the most boring job, documentation.

Update the documentation.

Add detailed documentation.

Starting with initial setup, add device usage, supported operating system, tool usage, tool setup. 

What else?

refer:

- [chenxiaolong/avbroot](https://github.com/chenxiaolong/avbroot)
- [chenxiaolong/my-avbroot-setup](https://github.com/chenxiaolong/my-avbroot-setup)
- [schnatterer/rooted-graphene](https://github.com/schnatterer/rooted-graphene)

**Comment by radioaddition** [comment]
> When setting PixeneOS up for the first time, the device must already be running the correct OS. Flash the original unpatched OTA or factory image if needed.

I believe this is unnecessary if you pass `--all`

**Comment by pixincreate** [comment]
Yes, but that should be an exception and I prefer to pass stuff that's only necessary.

There exist some formatting issues with the docs which will be addressed soon. I guess I'll add more detailed explanation in addition to that.

**Comment by radioaddition** [comment]
I was thinking more along the lines of "if you don't already have grapheneos installed you'll need to pass --all" instead of adding an extra step and an extra file to download

**Comment by pixincreate** [comment]
No, from the avbroot docs, you're expected to have a full working factory image installed prior to installing the patched the OTA.

**Comment by radioaddition** [comment]
Oh well I installed gos on my testing device which previously had divest this way so if I wasn't supposed to oops

**Comment by pixincreate** [comment]
Yes, this is unexpected as it is known to result in unintended issues. Especially with userdata for sure.

**Comment by radioaddition** [comment]
Oh well I had cleared userdata beforehand by unlocking the bootloader
